package com.frontier.settlements;

public enum SettlementBuilding
{
	NONE, TOWNHALL, WAREHOUSE, HOUSE, ROAD, BRIDGE, WALL,
    BARRACKS, APOTHECARY, BOUNTYHALL, WATCHTOWER,
    FARM, FISHERY, LODGE, GROVE, MINE,
    ALCHEMYLAB, ARCANUM, BLACKSMITH, CARTOGRAPHY, FLETCHERY, TANNERY,
    APIARY, COWBARN, CHICKENCOOP, SHEEPPASTURE, STABLE, PIGPEN, 
    BAKERY, ABATTOIR, GREENGROCERY, WOODSHOP, MASONRY,
    MARKETPLACE, TAVERN,
    CHURCH, LIBRARY, CEMETERY, WELL, FOUNTAIN;
}